WebApplication/Models/AbsenceRegModel.cs
using ClassLibrary.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc.Html;

namespace WebApplication.Models
{
    public class AbsenceRegModel
    {
        
        public AbsenceRegModel()
        {

        }
        public Lesson Lesson { get; set; }
        public List<AbsenceRegistration> AbsenceRegistrations { get; set; }
        public int CourseId { get; set; }
    }
}

WebApplication/Controllers/CourseController.cs
using ClassLibrary.Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class CourseController : Controller
    {
        Context context = Storage.Context.GetInstance();

        // GET: Course
        public ActionResult Course(int courseId)
        {
            Course course = context.GetCourseById(courseId);
            return View(course);
        }

        // GET: AbsencePerStudent
        public ActionResult AbsencePerStudent(int courseId)
        {
            Course course = context.GetCourseById(courseId);
            return View(course);
        }
    }
}

WebApplication/Controllers/HomeController.cs
using Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        Context context = new Context();

        public ActionResult Index(int? userId)
        {
            User user = context.GetUserById(userId);
            if (user != null)
            {
                return View(user);
            }
            else return RedirectToAction("Index", "Login");
        }
    }
}

WebApplication/Controllers/LessonController.cs
using ClassLibrary.Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.Web.WebPages.Html;

namespace WebApplication.Controllers
{
    public class LessonController : Controller
    {
        Context context = Storage.Context.GetInstance();

        // GET: Lesson
        public ActionResult Lesson(int courseId, int lessonId)
        {
            Lesson lesson = context.GetLessonById(lessonId);

            // Tilføjer en AbsenceRegistration til hver studerende til den valgt lektion, første gang underviseren åbner lektionen
            if(lesson.AbsenceRegistrations.Count == 0)
            {
                context.InitAbsenceRegistrationForLesson(lessonId, courseId);
            }

            AbsenceRegModel viewModel = new AbsenceRegModel() { Lesson = lesson, AbsenceRegistrations = lesson.AbsenceRegistrations, CourseId = courseId };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Lesson(AbsenceRegModel model)
        {
            context.AddAbsenceRegistrations(model.AbsenceRegistrations);

            // Sørger for at brugeren bliver på samme side
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

WebApplication/Controllers/LoginController.cs
using ClassLibrary.Model;
using Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class LoginController : Controller
    {
        Context context = Storage.Context.GetInstance();

        // GET: Index
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username)
        {
            User user = context.GetUserByUsername(username);
            if (user != null)
            {
                if(IsUserTeacher(user))
                {
                    return RedirectToAction("Index", "Teacher", new { teacherId = user.Id });
                }
                else
                {
                    return RedirectToAction("Index", "Student", new { studentId = user.Id });
                }
            }
            else return View();
        }

        public bool IsUserTeacher(User u)
        {
            return u.GetType() == typeof(Teacher);
        }
    }
}

WebApplication/Controllers/StudentController.cs
using ClassLibrary.Model;
using Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class StudentController : Controller
    {
        Context context = Storage.Context.GetInstance();

        // GET: Student
        public ActionResult Index(int? studentId)
        {
            Student student = context.GetStudentById(studentId);
            if (student != null)
            {
                return View(student);
            }
            else return RedirectToAction("Login", "Login");
        }
    }
}

WebApplication/Controllers/TeacherController.cs
using ClassLibrary.Model;
using Model;
using Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class TeacherController : Controller
    {
        Context context = Storage.Context.GetInstance();

        public ActionResult Index(int? teacherId)
        {
            Teacher teacher = context.GetTeacherById(teacherId);

            if (teacher != null)
            {
                return View(teacher);
            }
            else return RedirectToAction("Login", "Login");
        }
    }
}

WebApplication/Views/Course/AbsencePerStudent.cshtml
@{
    ViewBag.Title = "AbsencePerStudent";
}
@model ClassLibrary.Model.Course

<h3>Absence Per Student</h3>

<table>
    <tr><td width="200px"><b>Student name</b></td><td width="200px"><b>Absence rate in %</b></td><td width="200px"><b>Legal Absence rate in %</b></td></tr>
    @foreach (var s in Model.Students)
    {
        <tr>
            <td>
                @s.FullName
            </td>
            <td>    
                @{ var absenceRates = s.CalcAbsenceRate(Model); }
                @absenceRates[0]%
            </td>
            <td>
                @absenceRates[1]%
            </td>
        </tr>
    }
</table>

WebApplication/Views/Course/Course.cshtml
@{
    ViewBag.Title = "Home";
}

@model ClassLibrary.Model.Course

<h2>Register absence for:</h2>

    @if (Model.Lessons.Count > 0)
    {
        <table>
            <tr><td width="400px"><b>Lesson</b></td><td width="100px"><b>Status</b></td></tr>
            @{ var lessonsOrdered = Model.Lessons.OrderBy(l => l.Visisted); }
            @foreach (var lesson in lessonsOrdered)
            {
                <tr>
                    <td>
                        @Html.ActionLink(lesson.StartDate + " - " + lesson.EndDate, "Lesson", "Lesson", new { lessonId = lesson.Id, courseId = Model.Id }, null)
                    </td>
                    @if (lesson.Visisted)
                    {
                        <td>
                            &#9989;
                            @if (lesson.AbsenceRegistrations.Where(a => a.AbsenceState == null).Count() > 0)
                            {
                                <text>&#10071;</text>
} 
                        </td>
                    }
                    else
                    {
                        <td>&#10060;</td>
                    }
                </tr>
            }
        </table>
        <br />
        <br />
        @Html.ActionLink("See overview of absence per student", "AbsencePerStudent", new { courseId = Model.Id }, null)
    }
    else
    {
        <p>Course has no lessons registered ...</p>
    }
        

WebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@model Model.User

<h2>Home</h2>

<h3>Welcome @Html.DisplayFor(model => model.Username)</h3>

WebApplication/Views/Lesson/Lesson.cshtml
@{
    ViewBag.Title = "Home";
}

@model  WebApplication.Models.AbsenceRegModel

<h3>Register Absence for @Model.Lesson.StartDate - @Model.Lesson.StartDate</h3>


@using (Html.BeginForm())
{

       if(Model.AbsenceRegistrations.Count() > 0)
       {
            <table>
                <tr><td width="200px"><b>Student Name</b></td><td width="200px"><b>State</b></td></tr>
                @for (int i = 0; i < Model.AbsenceRegistrations.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.AbsenceRegistrations[i].Student.FullName)
                            @Html.HiddenFor(model => model.AbsenceRegistrations[i].Id)
                        </td>

                        <td>
                            @Html.EnumDropDownListFor(model => model.AbsenceRegistrations[i].AbsenceState)
                        </td>

                    </tr>
                }
            </table>
            <input type="submit" value="Save" />
       }
       else
       {
            <p>Your course has no students enrolled ...</p>
       }
}
<br/>
@Html.ActionLink("<< Back to lessons overview", "Course", "Course", new { courseId = Model.CourseId }, null)

  
  

WebApplication/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<!-- LOGIN FORM -->
<form method="post">
    Username: <input type="text" name="username" /><br />
    <input type="submit" />
</form>

WebApplication/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<form method="post">
    Username: <input type="text" name="username" /><br />
    <input type="submit" value="Log in" />
</form>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Absence Registration", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebApplication/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@model ClassLibrary.Model.Student

<h2>Student Administration</h2>

<h3>Welcome @Html.DisplayFor(model => model.FullName) (@Html.DisplayFor(model => model.Username))</h3>

@if (Model.AbsenceRegistrations != null)
{
    <table>
        <tr><th width="400px"><b>Lesson</b></th><th width="200px"><b>Absence state</b></th></tr>
        @foreach (var a in Model.AbsenceRegistrations)
        {
            <tr>
                @if (a.AbsenceState != null)
                {
                    <td>
                        @a.Lesson.StartDate - @a.Lesson.EndDate
                    </td>
                    <td>
                        @a.AbsenceState
                    </td>
                }
            </tr>
        }
       </table>
    <br/>
        <table>
            <tr><th width="200px"><b>Course</b></th><th width="200px"><b>Absence rate in %</b></th><th width="200px"><b>Legal absence rate in %</b></th></tr>
            @foreach (var c in Model.Courses)
            {
                <tr>
                    <td>
                        @c.Name
                    </td>
                    <td>
                        @{ var absenceRates = Model.CalcAbsenceRate(c); }
                        @absenceRates[0]%
                    </td>
                    <td>
                        @absenceRates[1]%
                    </td>
                </tr>
                            }
        </table>
                            } else
                            {
                                <p>No absence has been registered to your user yet ...</p>
                            }

WebApplication/Views/Teacher/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@model ClassLibrary.Model.Teacher

<h2>Teacher Administration</h2>

<h3>Welcome @Html.DisplayFor(model => model.FullName) (@Html.DisplayFor(model => model.Username))</h3>


    @if (Model.Courses.Count > 0)
    {
        <table>
            <tr><td width="200px"><b>Course</b></td><td width="200px"><b>Average absence in %</b></td></tr>
            @foreach (var course in Model.Courses)
            {
                <tr>
                    <td>
                        @Html.ActionLink(@course.Name, "Course", "Course", new { courseId = course.Id }, null)
                    </td>
                    <td>
                        @course.CalcAverageAbsenceRate()%
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>You have no courses registered ...</p>
    }
           